import "./AfterHero.css";
import Card1 from "./Cards/Card1";
import Card2 from "./Cards2/Cards2";
import pic1 from "../../Assets/Picture1.png";
import pic2 from "../../Assets/Picture2.png";
import pic3 from "../../Assets/Picture3.png";
import pic4 from "../../Assets/Picture4.png";
import { useState } from "react";
import PaymentDetailsModal from "../payment-details-modal/PaymentDetailsModal"; // adjust if needed
import { useNavigate } from "react-router-dom";

export default function AfterHero() {
  const [showModal, setShowModal] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState(null);
  const navigate = useNavigate();

  const handleChoosePlan = (planName) => {
    setSelectedPlan(planName);
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setSelectedPlan(null);
  };

  const handleConfirm = () => {
    navigate(`/register?plan=${selectedPlan.toLowerCase()}`);
    setShowModal(false);
  };

  return (
    <div className="main-div-afterHero">
      <div className="all-data-inside">
        {/* About Us Section */}
        <div className="about-us-section" id="About-Us">
          <div className="main-heading1">
            <p>About Us – Sea Shell Earn Smart</p>
          </div>
          <div className="about-content">
            <p>
              At Sea Shell Earn Smart, we turn the beauty of the ocean into a thriving global business. 
              We specialize in sourcing rare and precious seashells from the Indo-Pacific (Philippines, 
              Indonesia, Sri Lanka, Maldives), select African and Oceanian regions via licensed exporters.
            </p>
            <p>
              Our dedicated team works closely with licensed collectors and trusted exporters, ensuring 
              every shell we trade is authentic, ethically sourced, and of the highest quality. These 
              exquisite pieces are sought after by collectors, jewelers, and décor makers across the 
              globe, creating a steady and profitable market.
            </p>
            <p>
              But we don't just trade shells — we build opportunities. Through our profit-sharing model, 
              we give our investors a chance to share in the success of our global operations. With 
              transparency, trust, and proven trade records at the heart of our work, Sea Shell Earn 
              Smart offers a rare combination of beauty, business, and financial growth.
            </p>
            <div className="vision-mission">
              <div className="vision">
                <h4>Our Vision:</h4>
                <p>To become the world's most trusted name in the rare seashell trade, bringing ocean treasures to every corner of the world.</p>
              </div>
              <div className="mission">
                <h4>Our Mission:</h4>
                <p>To connect nature's wonders with global markets while creating wealth for our investors.</p>
              </div>
            </div>
          </div>
        </div>

        {/* Earnings Structure Section */}
        <div className="earnings-section">
          <div className="main-heading1">
            <p>How You Earn With Us</p>
          </div>
          <div className="earnings-content">
            <p className="earnings-intro">
              Our transparent and rewarding earning structure is designed to maximize your returns through 
              multiple income streams. Here's how your investment grows with Sea Shell Earn Smart:
            </p>
            
            <div className="earnings-grid">
              <div className="earning-card primary-earning">
                <div className="earning-icon">
                  <span>💰</span>
                </div>
                <div className="earning-details">
                  <h4>Daily Investment Returns</h4>
                  <div className="percentage">2%</div>
                  <p>
                    Receive a guaranteed <strong>2% daily return</strong> on your total investment amount. 
                    This consistent income stream is automatically calculated and credited to your account 
                    every 24 hours, ensuring steady growth of your portfolio.
                  </p>
                  <div className="earning-example">
                    <small>Example: $1,000 investment = $20 daily returns</small>
                  </div>
                </div>
              </div>

              <div className="earning-card referral-earning">
                <div className="earning-icon">
                  <span>🤝</span>
                </div>
                <div className="earning-details">
                  <h4>Referral Commission</h4>
                  <div className="percentage">20%</div>
                  <p>
                    Earn an additional <strong>20% commission</strong> on the daily profits generated by 
                    investors you refer to our platform. When your referrals earn their 2% daily returns, 
                    you automatically receive 20% of their profit as your referral bonus.
                  </p>
                  <div className="earning-example">
                    <small>Example: Referral earns $50 daily = You get $10 bonus</small>
                  </div>
                </div>
              </div>
            </div>

            <div className="earnings-benefits">
              <div className="benefit-item">
                <span className="benefit-icon">🔄</span>
                <span>Automatic daily calculations and payouts</span>
              </div>
              <div className="benefit-item">
                <span className="benefit-icon">📊</span>
                <span>Real-time tracking in your dashboard</span>
              </div>
              <div className="benefit-item">
                <span className="benefit-icon">🚀</span>
                <span>Compound growth potential</span>
              </div>
              <div className="benefit-item">
                <span className="benefit-icon">🎯</span>
                <span>No hidden fees or charges</span>
              </div>
            </div>
          </div>
        </div>

        <div className="main-heading1">
          <p id="Plans">Investment Plan</p>
        </div>

        <div className="sub-heading1">
          <p>
            Choose Your Plan, Grow Your Income Daily. Simple, Secure, and
            Scalable Returns.
          </p>
        </div>

        <div className="cardsInside">
          <Card1
            name="Bronze"
            p1="Start Small, Earn Steady."
            p2="Perfect for first-time investors looking for daily returns."
            onChoose={handleChoosePlan}
          />
          <Card1 name="Silver" p1="Double the Growth" p2="Step up your earnings with consistent daily profits." onChoose={handleChoosePlan} />
          <Card1 name="Gold" p1="Shine with Bigger Profits." p2="Reliable returns with serious momentum." onChoose={handleChoosePlan} />
          <Card1 name="Platinum" p1="Earn Like a King." p2="For those who play big and win big." onChoose={handleChoosePlan} />
          <Card1 name="Diamond" p1="Diamond Investment Plan" p2="Where your money shines as bright as your future." onChoose={handleChoosePlan} />
          <Card1 name="Elite" p1="Elite Investment Plan" p2="Invest like a pro with elite tools, insights, and returns." onChoose={handleChoosePlan} />
        </div>

        {showModal && (
          <PaymentDetailsModal
            planName={selectedPlan}
            onClose={handleCloseModal}
            onConfirm={handleConfirm}
          />
        )}

        <div className="Second-cardsInside">
          <div className="main-heading1">
            <p>Why Choose Us</p>
          </div>

          <div className="card2-grid-wrapper">
            <Card2 img={pic1} para1="Transparent profit system" para2="No hidden fees. Know exactly what you earn and how you earn. Everything is clearly tracked and displayed." />
            <Card2 img={pic2} para1="Fixed Daily Income" para2="Enjoy a guaranteed 2% daily return on your investment without market risk or fluctuation." />
            <Card2 img={pic3} para1="Real Time Dashboard Tracking" para2="Monitor your earnings, referrals, and withdrawals with a live, easy-to-use dashboard anytime, anywhere." />
            <Card2 img={pic4} para1="Trusted by Hundreds of Investors" para2="Our platform is backed by a strong and growing community who trust us for timely payouts and reliable service." />
          </div>
        </div>
      </div>
    </div>
  );
}